name: Cron Test

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    name: "Nuxt"
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Node Version
        shell: bash
        run: node -v
