name: Build

on:
  schedule:
    - cron: "*/1 * * * *"

permissions:
  contents: read

jobs:
  build:
    name: "Nuxt Feature"
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
