name: Label Workflow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for this workflow"
        required: true

run-name: Deploying-${{ github.event.inputs.tag }}

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: write

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Print Label
        run: |
          echo "The Github workflow ${{ github.event.inputs.tag }}"

      - name: Create GitHub Release
        uses: actions/github-script@v7
        with:
          script: |
            const releaseResponse = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "1.2.0",
              name: `Release 1.2.0`,
              body: `### Changelog\n Test`,
              draft: false,
              prerelease: false,
            });
