name: Manual Job Trigger with Dependencies

on:
  workflow_dispatch:
    inputs:
      job_to_run:
        description: "Choose a job to run"
        required: true
        type: choice
        options:
          - job1
          - job2
          - job3
  release:
    types: [created]

jobs:
  job1:
    name: Run Job 1
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job_to_run == 'job1' || github.event.inputs.job_to_run == 'job2' }}
    steps:
      - name: Job 1 Step
        run: echo "Job 1 is running!"

  job2:
    name: Run Job 2
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ github.event.inputs.job_to_run == 'job2' }}
    steps:
      - name: Job 2 Step
        run: echo "Job 2 is running!"

  job3:
    name: Run Job 3
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job_to_run == 'job3' }}
    steps:
      - name: Job 3 Step
        run: echo "Job 3 is running!"
