name: Manual Job Trigger with Dependencies

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        default: "development"
      build_number:
        description: "Build number"
        required: false

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Build number: ${{ github.event.inputs.build_number }}"
