# name: Manual Job Trigger with Dependencies

# on:
#   workflow_dispatch:
#     inputs:
#       job_to_run:
#         description: "Choose a job to run"
#         required: true
#         type: choice
#         options:
#           - job1
#           - job2
#           - job3
#   release:
#     types: [created]

# jobs:
#   job1:
#     name: Run Job 1
#     runs-on: ubuntu-latest
#     if: ${{ github.event.inputs.job_to_run == 'job1' || github.event.inputs.job_to_run == 'job2' }}
#     steps:
#       - name: Job 1 Step
#         run: echo "Job 1 is running!"

#   job2:
#     name: Run Job 2
#     runs-on: ubuntu-latest
#     needs: job1
#     if: ${{ github.event.inputs.job_to_run == 'job2' }}
#     steps:
#       - name: Job 2 Step
#         run: echo "Job 2 is running!"

#   job3:
#     name: Run Job 3
#     runs-on: ubuntu-latest
#     if: ${{ github.event.inputs.job_to_run == 'job3' }}
#     steps:
#       - name: Job 3 Step
#         run: echo "Job 3 is running!"

name: Label Workflow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for this workflow"
        required: true

run-name: Deploying-${{ github.event.inputs.tag }}

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Add label to workflow run
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.run_id }}/labels \
            -d '{"labels": ["${{ github.event.inputs.tag }}"]}'
